### ISSUE TITLE
iOS 8.0 CocoaPods platform of the target

### ISSUE THREAD

**Issue by aagahi** [sascha/DrawerController#10]
DrawerController seems to work pretty with deployment target 7.0+ in xcode so far...

I was wondering if there is limitations requiring 8.0 as minimal target when dealing with cocoapods?

**Comment by sascha** [comment]
Yes, unfortunately there is. You might want to take a look at http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

> CocoaPods only supports Swift on OS X 10.9 and newer, and iOS 8 and newer.
