### ISSUE TITLE
Navigation Drawer Button

### ISSUE THREAD

**Issue by daimagine** [sascha/DrawerController#11]
Thank you for your awesome works. I am learning swift and find this navigation drawer helpful. But I need to change the navigation drawer button. Could you give me an insight how to do it or maybe you have a plan to make it dynamic?

**Comment by maltebaumann** [comment]
Hi daimagine, you can use any button you want to open the menu. Just take a look at the KitchenSink example. The top left and right buttons are set up in the ```setup*MenuButton``` functions. Any button can be used. They just need to call the drawer controllers toggle functions (```self.evo_drawerController?.toggleDrawerSide(.Left, animated: true, completion: nil)```).

If you want to customize the animated menu button you would need to dig into its code though. It's drawn manually and therefore the layout code would need to be changed.
