### ISSUE TITLE
SideViewController content gets "pushed down" when first displayed

### ISSUE THREAD

**Issue by bryanbartow** [sascha/DrawerController#12]
The first time either a left or right view controller is displayed, its content appears to be pushed down and into place once the VC is finished animating in.  This looks like an issue with ``MMDrawerController`` as well.  The comment [here](https://github.com/mutualmobile/MMDrawerController/issues/203#issuecomment-69500579) seems to fix it.  The short and sweet is this:

Add the following line to the ``viewWillAppear:animated`` method of your SideViewController:
```Swift 
self.navigationController?.view.layoutSubviews()
```
So it looks something like this:
```Swift
override func viewWillAppear(animated: Bool) {
    super.viewWillAppear(animated)
        
    // Workaround for DrawerController issue with iOS 8
    self.navigationController?.view.layoutSubviews()
}
```

**Comment by sascha** [comment]
Thanks! layoutSubviews() should not be called directly though, which is why I'm using setNeedsLayout()
