### ISSUE TITLE
I can't  use this with cocoapods.

### ISSUE THREAD

**Issue by zhouzizi** [sascha/DrawerController#14]
platform :ios, '8.0'
pod 'DrawerController', '~> 1.0.1'

var drawer =  DrawerController(centerViewController: main, leftDrawerViewController: left)

xcode can't recognize  DrawerController Class！

**Comment by sascha** [comment]
Did you import the generated module in the file where you want to use it like this?

```swift
import DrawerController
```

**Comment by zhouzizi** [comment]
Cannot load underlying module for 'DrawerController'。。。。QAQ

**Comment by sascha** [comment]
Do you use CocoaPods 0.36 and did you add `use_frameworks!` to your Podfile?

**Comment by zhouzizi** [comment]
e. 
pod --version
0.36.3
Podfile:
use_frameworks!
platform :ios, '8.0' 
pod 'DrawerController', '~> 1.0.1'

**Comment by sascha** [comment]
Sorry, I can't reproduce this. Could you send me a sample project?

**Comment by wuyisheng** [comment]
I haved the same problem:
pod version is 0.37.1
use DrawerController (1.0.4)
when import DrawerController ,xcode show a error:
"cannot load undelying module for ‘DrawerController’"

**Comment by wuyisheng** [comment]
This is because the project did not clean，select product->Clean，then rebuild the project，solve this problem
