### ISSUE TITLE
Use of the drawer controller w/ a login screen

### ISSUE THREAD

**Issue by mattdeboard** [sascha/DrawerController#16]
Hey there. I was able to use this framework to remove a bunch of code written in-house that was getting a little confusing, so thanks for that.

One question I have is: How would I go about using this in conjunction with a login screen? That is, the login screen is the entry point to the app. The navigation controller immediately after the login screen (upon successful login of course) is `MainNavController`. This is the controller we want to use in conjunction with `DrawerController`.

Now if I instantiate `DrawerController` like so, it works just beautifully:

```swift
      self.drawerController = DrawerController(
        centerViewController: self.helperFunctionThatReturnsMainNavController()!,
        leftDrawerViewController: self.leftViewController()
      )
      self.drawerController.showsShadows = true
      self.drawerController.restorationIdentifier = "Drawer"
      self.drawerController.maximumLeftDrawerWidth = UIScreen.mainScreen().bounds.width * 0.33
      self.drawerController.openDrawerGestureModeMask = OpenDrawerGestureMode(rawValue: 0b1111)
      self.drawerController.closeDrawerGestureModeMask = CloseDrawerGestureMode(rawValue: 0b1111111)

      window?.rootViewController = self.drawerController
      window?.makeKeyAndVisible()

```

However, this of course doesn't allow our login screen the chance to display. I have tried making another nav controller that has the login screen as its root view, and instantiating `DrawerController` with that, but that didn't seem to work well.

I realize this may be a really hard question to answer without actually seeing the things, but I would appreciate any input you could give.

**Comment by maltebaumann** [comment]
Hi Matt, it's hard to suggest a solution without seeing your code, but I'll try.

I usually try to separate the login/registration and main app view controller hierarchy. So upon first launch the app starts with a basic UINavigationController containing the login screens as the windows root view controller. When the user logs in I replace the root nav controller with a DrawerController. 

Another solution may be to use of the DrawerController as a root and present any login UI modally above it.

I hope this gives you a basic idea on how to do this. If you need any further help, please let me know or drop me an email.
