### ISSUE TITLE
When I push from CenterViewControlller

### ISSUE THREAD

**Issue by zhouzizi** [sascha/DrawerController#17]
When I push from CenterViewControlller,the next viewcontroller will recognize the pan gesture... I don't need it ...

**Comment by maltebaumann** [comment]
Hi there, you can set the active Gestures via the openDrawerGestureModeMask. If you set it to none after pushing a new view controller, the DrawerController won't react to any panning.

**Comment by sascha** [comment]
@zhouzizi: GitHub Issues is meant to be a bug tracker. It is a way to keep track of tasks, enhancements, and bugs for the project. If you have general questions about using DrawerController, you should ask those questions over at http://stackoverflow.com. Give your questions appropriate tags like `ios`, `swift` and `DrawerController` and ask a **clear question** (this issue does not even contain a question). Write down what you've tried to solve your problem and add some sample code. Nobody will want to solve your problems for you if you don't put in some effort yourself. Also, you might want to have a look at http://stackoverflow.com/help/how-to-ask :wink:
