### ISSUE TITLE
centerViewController.navigationController?.pushViewController not working

### ISSUE THREAD

**Issue by jasoncheng** [sascha/DrawerController#18]
Dear sir:

> i use your DrawerController, and appreciate for your contribute.
> i’m newbie on swift and iOS, here is my problem, and this issue confuse me for few days, please help
> (swift 1.2 / xcode 6.3.1)

Thanks
—————————————————————————————————

A: centerViewController(main)
B: leftDrawerViewController(tableViewController)
C: NotificationController 

when i click on B item, i hope can let A => C, so i try

=== B ===
```
// call A func 
let v = self.storyboard?.instantiateViewControllerWithIdentifier("main") as! ViewController
v.showNotification()

// Or directly pushViewController from B

let view = self.storyboard?.instantiateViewControllerWithIdentifier("notification") as! NotificationController
self.evo_drawerController?.centerViewController?.navigationController?.pushViewController(view, animated: true)
```

=== A ===
```
func showNotification(){
  // not work
  let view = self.storyboard?.instantiateViewControllerWithIdentifier("notification") as! NotificationController
  self.navigationController?.pushViewController(view, animated: true)

  // not work too
  self.performSegueWithIdentifier("toNoti", sender: self)
}
```

**Comment by sascha** [comment]
Hi @jasoncheng,

sorry, I'm not quite sure I understand your issue. Do you want to present another view controller in the center by tapping a button in the view controller on the left side? If so, doing this in your left view controller should work:

```
let viewController = UIViewController()
self.evo_drawerController?.setCenterViewController(viewController, withCloseAnimation: true, completion: nil)
```

**Comment by jasoncheng** [comment]
At the same time, i resolved this problem by using delegate.
thank you so much.
