### ISSUE TITLE
Is it suitable to use this in conjunction with Storyboard driven VCs?

### ISSUE THREAD

**Issue by nickvelloff** [sascha/DrawerController#20]

**Comment by sascha** [comment]
It depends on what you mean by that. You can't drop the DrawerController into your storyboard and connect left, center and right view controllers with other view controllers in your storyboard and it also does not come with any custom segues to use in IB. But you can use `-[UIStoryboard instantiateInitialViewController]` and set that as any of the child view controllers of `DrawerController` in your app delegate and then go from there.
