### ISSUE TITLE
How to change color of the Drawer Icon (three horizontal lines)

### ISSUE THREAD

**Issue by hassanabidpk** [sascha/DrawerController#22]
I am using DrawerController for my project.

I am wondering about 
1 - How to change color of Drawer icon ( three horizontal lines). For now they are grey color
2- How can I hide Right Side Drawer  ?

Thanks

**Comment by maltebaumann** [comment]
Hi,

1 - Take a look in the ```AnimatedMenuButton``` class, if you're using the animated drawer icon. layer.strokeColor is the line you'd need to change. Or feel free to add some customization options to the AnimatedMenuButton and submit a pull request :)

2 - I'd suggest to check out the KitchenSink sample project. Everything can be found there. It's unclear to me if you want to avoid having a right side drawer at all or just want to close the right side.

**Comment by hassanabidpk** [comment]
Thanks @maltebaumann  !  I am loving it so far. Have few suggestions that I will tell you at some point.
