### ISSUE TITLE
iOS 7.1 support

### ISSUE THREAD

**Issue by TomDoes** [sascha/DrawerController#24]
Hi, 

I've build the project successfully on a phone with iOS 7.1 however when I want to upload I get an error because frameworks are not supported in < iOS 8.0 apps. Normally you would copy all the sources of the imported project to your app project and you would be fine.

Here come's my problem: When I do this I get ambigiuous errors for the evo_drawerController. Line 39 of DrawerController.swift and my own code.

In the side menu controller:

      func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {

        var navigationController = UINavigationController()
        navigationController.navigationBar.translucent = false;
        
        navigationController.pushViewController(viewControllers[indexPath.row], animated: false)
        tableView.cellForRowAtIndexPath(indexPath)?.contentView.backgroundColor = UIColor.wttvMenuSelectedColor()

        self.evo_drawerController?.setCenterViewController(navigationController, withCloseAnimation: true, completion: nil)

    }

and my center UIViewController

    func leftDrawerButtonPress(sender: AnyObject?) {
        self.evo_drawerController?.toggleDrawerSide(.Left, animated: true, completion: nil)
    }

 Obviously I'm doing something wrong because a a framework it's working fine. Could your provide an example of how to add the sources to my own project and what changes should be made?

**Comment by sascha** [comment]
What exactly do the errors say? As you said, all you have to do to support iOS 7 is drop the DrawerController Swift files into your project and everything should work.

**Comment by TomDoes** [comment]
I think the root cause is: 'ambiguous use of evo_drawerController'

for line 24 and 39 of DrawerController.swift

And i get errors for these lines in my own code (which works fine when drawercontroller is imported as a framework)->
for         
self.evo_drawerController?.setCenterViewController(navigationController, withCloseAnimation: true, completion: nil)
 could not find member 'setCenterViewController'

for 
        self.evo_drawerController?.toggleDrawerSide(.Left, animated: true, completion: nil)

could not find member left

**Comment by sascha** [comment]
You probably define your own property in a UIViewController called 'evo_drawerController' which is why the compiler doesn't know which one to use. If you use frameworks, this is not an issue because all methods and properties created by DrawerController are then namespaced to 'DrawerController' but this is not the case when importing the files into your project.

So: Take a look at your code and see if you define a property called 'evo_drawerController' somewhere and give it another name.

**Comment by TomDoes** [comment]
I've thought of that, but it seems this is not the case.

![schermafbeelding 2015-07-02 om 11 43 33](https://cloud.githubusercontent.com/assets/5182083/8474322/9345d4b4-20af-11e5-827a-ddc7c1ebd4b5.png)

**Comment by sascha** [comment]
Not sure what's wrong then. Could you reproduce the error in a reduced sample project and send me a link to that please?

**Comment by TomDoes** [comment]
Just use your kitchensink example, copy the Drawercontroller files, remove the framework and delete the import line from the appdelegate. This should produce the same behaviour

**Comment by sascha** [comment]
Just gave that a try and it builds just fine. Did you clean your project and/or removed your DerivedData folder after switching from frameworks?

**Comment by TomDoes** [comment]
It was the derived data... removed it and everything works fine now.

Thank you for your time :)

**Comment by sascha** [comment]
No problem :)
