### ISSUE TITLE
How to disable MMDrawerController at some view?

### ISSUE THREAD

**Issue by htarwara6245** [sascha/DrawerController#26]
https://github.com/mutualmobile/MMDrawerController/issues/391

**Comment by maltebaumann** [comment]
Hey, you could try to set the `gestureShouldRecognizeTouchBlock`to always return `false`.

**Comment by gregorpichler** [comment]
@maltebaumann I've tried this in my recent project, but I'm still able to swipe and the menu shows up.

```
self.evo_drawerController?.gestureShouldRecognizeTouchBlock = {(_,_,_) in
            return false
        }
```

**Comment by maltebaumann** [comment]
Hey you need to set ```openDrawerGestureMode``` to custom, as stated in the documentation:

"Note that either `openDrawerGestureModeMask` must contain `OpenDrawerGestureModeCustom`, or `closeDrawerGestureModeMask` must contain `CloseDrawerGestureModeCustom` for this block to be consulted."
