### ISSUE TITLE
Trying to use with a tabBarController

### ISSUE THREAD

**Issue by cwoloszynski** [sascha/DrawerController#29]
I am trying to use this as a menu controller in a design that has a tabBar controller at the root, then nav controllers at the top of each tabBar view controller.  

The reveal excludes the tabBar area so the bottom bar stays in place while the rest slides.  This is different than how the Facebook app behaves.  Once the menu is open, I don't want the user to be able to change the tab bar controller (and leave one tab bar with the menu open, for example). 

Any ideas if this design can be used to extend its reach to grab the tabbarcontroller buttons and slide them also (and disable interaction with them)?

**Comment by sascha** [comment]
Hi @cwoloszynski, I'm not sure I completely understand what you are trying to do. Do you want the tab bar to move to the side together with the rest (just like the Facebook app)? If so, why don't you just use the `DrawerController` as your `rootViewController` and set its center view controller to an `UITabBarController` (with `UINavigationController`s as its children)?

**Comment by cwoloszynski** [comment]
Sascha:

Sorry I was not clear enough.  I have two competing needs.  One is to have the menu slide the tab bar to the side when opening the menu, the other is to allow the menu to interact with the navigation controller to segue to new screens from a menu selection.  

it seems that I have to put the DrawerController as the root view controller (per your suggestion) to get the Drawer to move the windows properly.  However, if I do that, I think I need a mechanism to communicate the selection of the menu item back down to the view controller within the navigation controller (so it can use segues to support forward/back operations) and I need to somehow instantiate the drawer button in the view controllers in the navigation controller and propagate the touches back to the Drawer Controller.  Do you have any suggestions on how to do that latter part?

Thanks for the GREAT project.  I am very excited to get to use it. 

Charlie

**Comment by cwoloszynski** [comment]
I found your UIView extension that addresses my concern (evo_drawerController) about how to bubble the menu button to the DrawerController.  I guess I should have done some additional research.  

Thanks again for this great project.
