### ISSUE TITLE
Interested in a pull-request for configuring center, left, and right view controllers via storyboard?

### ISSUE THREAD

**Issue by cwoloszynski** [sascha/DrawerController#30]
I would like to configure the center, left and right view controllers within a storyboard.  I have seen some code that uses custom segues (with specific segue identifiers) that might allow the user to configure this all within a storyboard.  

Is this something you would be willing to incorporate into your project, if I offered a pull request for a design that you thought was acceptably clean?

**Comment by sascha** [comment]
Yes, absolutely. Always appreciate pull requests

**Comment by sascha** [comment]
Closing this issue because of PR #31
