### ISSUE TITLE
Black edge line blinks when using slideVisualStateBlock

### ISSUE THREAD

**Issue by hyouuu** [sascha/DrawerController#32]
When dragging the left drawer out, there is a black edge line appears and disappears rapidly - feels like the left and center view are not moving at the exact same speed?

Also when releasing the view in an dragging, the view restore velocity feels kind of weird - maybe too fast? Looks like the params are the same as MMDrawerController, any thoughts what caused this?

Thanks for the Swift version!

**Comment by sascha** [comment]
@hyouuu: I don't really see the black line when dragging the left drawer out, but I assume that it could be a rounding problem. Could you give https://github.com/sascha/DrawerController/tree/black-line-glitch a try and see if that fixes that?

Regarding the velocity: DrawerController specifies a minimum velocity. If the dragging velocity is below that, it might feel weird because it is in fact opening/closing faster than you would expect.

**Comment by hyouuu** [comment]
Thanks for the response. I tried the version but it still shows up. If your centerVC and leftVC have similar color I guess it'd be hard to notice - probably try contradicting colors with another contradicting background window color?

**Comment by hyouuu** [comment]
Don't see the issue anymore - not sure how it got fixed :) Thanks for the component!

**Comment by hyouuu** [comment]
Actually, the fix was from my own code compensation... So I further dig into it, and it's the issue of the centerVC's frame not the side (the side's x is always an integer number) - the centerVC was set the centerX, which often gets to .5 and I guess iOS always floor it. Fixed with https://github.com/sascha/DrawerController/pull/53

**Comment by harrisrap** [comment]
I tried adding this fix, and it had a huge negative impact on performance. Dragging becomes very choppy.
A better fix is this, which I tried and works perfectly, with no negative impact on performance:

self.centerContainerView.frame.origin.x = newFrame.origin.x

**Comment by hyouuu** [comment]
Makes sense - let me update & thanks!

**Comment by hyouuu** [comment]
BTW is this a new feature in Swift? Previously we can't set frame.origin.x directly, and didn't see mentions about this, but it works perfectly :)

**Comment by hyouuu** [comment]
FYI, I've added a CGRect extension to my project to replace rect assignments according to your performance report ;)

extension CGRect {
  // Firstly detect if rect equals, noop;
  // Then if size equals, only update origin, which has perf benefits for UIView frames
  func set(newRect: CGRect) {
    if newRect == self {
      return
    }
    if newRect.size == self.size {
      self.origin = newRect.origin
    }
    self = newRect
  }

**Comment by harrisrap** [comment]
Awesome!  I’m glad my suggestion helped.  

Fyi, it looks like you are missing an else after that last if ;-)

**Comment by hyouuu** [comment]
Yes ;) Also need a `mutating` before the func

**Comment by domingguss** [comment]
I had this too, and  I think it is happening due to the `drawerDampingFactor`.

`d.drawerDampingFactor = 10000.0` would maybe fix this?
