### ISSUE TITLE
pushViewController call from centerViewController could make the view unresponsive

### ISSUE THREAD

**Issue by hyouuu** [sascha/DrawerController#33]
When the leftDarwerViewController is disappearing (sliding out), quickly try to call pushViewController from the centerViewController sometimes make the whole app unresponsive, which is likely caused by animation conflicts - could we add a call back when the animation finishes completely?

**Comment by sascha** [comment]
Sorry, I'm not able to reproduce this. But please feel free to submit a pull request :-)
