### ISSUE TITLE
setGestureShouldRecognizeTouchBlock is not supported

### ISSUE THREAD

**Issue by oeresundsgruppen** [sascha/DrawerController#35]
this function is part of orig objectC impl, but not in swift....

**Comment by maltebaumann** [comment]
Hi, this is function is implemented via the `gestureShouldRecognizeTouchBlock` property on the DrawerController.

**Comment by oeresundsgruppen** [comment]
Yes, works as: 
centerContainer?.gestureShouldRecognizeTouchBlock = checkGestureFunc

private func checkGestureFunc(drawer: DrawerController, gesReg: UIGestureRecognizer, touch: UITouch) -> Bool
    {
        let point = gesReg.locationInView(drawer.view)
        print (point.x)
        return true
    }

Problem I have is setting centerviewer to pageviewcontroller; not sure if this can ever be supported. When sliding left, the pageviewer reacts, but not the drawercontroller to the left....
