### ISSUE TITLE
Ambiguous use of 'evo_drawerController'

### ISSUE THREAD

**Issue by shahdhiren** [sascha/DrawerController#37]
I have 2 targets in my application, one is of main application target and one is of Unit Test target of my application. I have used DrawerController in my application.

Now, my main application target is running fine without any error. But when I try to run the Unit Test target, I am getting the "ambiguous use of 'evo_drawerController' " 

Below is the exact error from build logs:

               /Users/dhirenshah/Documents/git/ThirdParties/DrawerController/DrawerController.swift:39:35: error: ambiguous use of 'evo_drawerController'
        if let drawerController = self.evo_drawerController {
                                  ^
              /Users/dhirenshah/Documents/git/ThirdParties/DrawerController/DrawerController.swift:24:9: note: found this candidate
    var evo_drawerController: DrawerController? {
        ^
           PCities.UIViewController:2:16: note: found this candidate
               public var evo_drawerController: PCities.DrawerController? { get }

I tried few of the solutions but didn't work. I followed this link but did'nt worked: http://stackoverflow.com/questions/24087011/ambiguous-use-of-propertyname-error-given-overridden-property-with-didset-ob

**Comment by sascha** [comment]
Did you add the DrawerController to both targets (app and unit tests) at the same time? That will usually give you that error. You should only have to add it to the app target, because the unit tests automatically include everything that's in the app target.
