### ISSUE TITLE
Does not working “back swipe” when NavigationBar is hidden

### ISSUE THREAD

**Issue by nullproduction** [sascha/DrawerController#38]
Hello! Thank you for DrawerController.
Does not working “back swipe” in UINavigationController when NavigationBar is hidden.

I made demo project and video with bug:
Video demo - https://www.youtube.com/watch?v=HgayLC5a_Ik
Demo project - https://github.com/nullproduction/SliderApp

How I can fix it problem?

**Comment by maltebaumann** [comment]
Hi nullproduction. This seems to be a common UIKit issue. Not our framework breaks the back swipe, but hiding the navigation bar in general does. See this discussion, which includes some workarounds:

http://stackoverflow.com/questions/24710258/no-swipe-back-when-hiding-navigation-bar-in-uinavigationcontroller

**Comment by nullproduction** [comment]
Hi maltebaumann. I tried it solution but it does not working with DrawerController.

```
self.navigationController!.interactivePopGestureRecognizer?.delegate = nil
```

https://github.com/nullproduction/SliderApp/blob/master/SliderApp/FirstViewController.swift#L35
