### ISSUE TITLE
There is no animation when you set a new center view controller..

### ISSUE THREAD

**Issue by aornano** [sascha/DrawerController#39]
If you want to set a new center view controller, apart from side closing animation, there are no animations available to show old center view controller go out and new center view controller showed up. Do you have in project to do it? 

For example inside private func setCenterViewController(centerViewController:

after ... self._centerViewController!.didMoveToParentViewController(self) 

let parent = self
let transition = CATransition()
transition.duration = 0.3
transition.timingFunction = CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseInEaseOut)
transition.type = kCATransitionPush
transition.subtype = kCATransitionFromTop (or any other customizable type inherited..)
transition.fillMode = kCAFillModeForwards
transition.removedOnCompletion = true
parent.view.layer.addAnimation(transition, forKey: nil)

This is just only an idea but i dont have yet try it.. so hope it can be useful..

**Comment by maltebaumann** [comment]
Hi, you can easily add such an animation yourself, by using the standard animation techniques. Therefore we don't see a need to add such functionality, but thanks for the input!
