### ISSUE TITLE
How to Remove drawer in certain screen within navigation controller stack?

### ISSUE THREAD

**Issue by shahdhiren** [sascha/DrawerController#40]
I have Left View Controller and Centre Navigation Controller. In center navigation controller, I am pushing 2 screens and in 2nd screen onwards, I dont want side menu to be appear. How to remove that in current code? I tried 2-3 alternatives but having weird behavior.

**Comment by maltebaumann** [comment]
Hi, you could reset your drawer controller setup and replace the windows root view controller. If you just don't want the user to be able to open the drawer, you could also set the `openDrawerGestureModeMask` to custom and return `false` in the `gestureShouldRecognizeTouchBlock`. This way, the user is not able to open the drawer, but you still keep your view controller hierarchy and can easily enable the drawer controller again.

**Comment by shahdhiren** [comment]
Thanks for prompt reply. 

I got your point, but I am not sure exactly what GestureRecognizer and Touch should be passed in gestureShouldRecognizeTouchBlock block. I tried passing nil in both but compilation error. This is property, so I am setting it in particular view controller where I don't won't touch.

**Comment by maltebaumann** [comment]
You don't need to call, but set the `gestureShouldRecognizeTouchBlock`. E.g. (rough, not tested)
```
drawerController. gestureShouldRecognizeTouchBlock = { _, _ in return false }
```
