### ISSUE TITLE
Removing Drawer on particular screen disables the click event on drawer items

### ISSUE THREAD

**Issue by shahdhiren** [sascha/DrawerController#42]
Hi,

As per our previous conversation (https://github.com/sascha/DrawerController/issues/40#issuecomment-168214368), I have used below code to enable and disable the Drawer on particular screen. This is working fine. Below is the code I had used:

```
       if !enable {
            drawer.openDrawerGestureModeMask = .Custom
            drawer.gestureShouldRecognizeTouchBlock = { _, _, _ in return false }
        } else {
            drawer.openDrawerGestureModeMask = [.PanningNavigationBar, .PanningCenterView]
            drawer.gestureShouldRecognizeTouchBlock = { _, _, _ in return true } 
        }
```

But due to this there has been a side effect of above code that, once I visited the screen where I disable the drawer, then onwards, the click event on the Drawer is not working. None of the Table cell is clickable. Is there anything wrong in above code? Or is there something I am missing?

I tried to debug the source, but didn't helped much. I am not able to figure out the comment that is written for "openDrawerGestureModeMask" property, that is stated as below:

```
How a user is allowed to open a drawer using gestures.
    
By default, this is set to `OpenDrawerGestureModeNone`. Note these gestures may affect user interaction with the `centerViewController`, so be sure to use appropriately.
```

Here you say that it is default to None, but in enum there is no value like None in that enum. Is it a typo? or what?

**Comment by Flitskikker** [comment]
I'm disabling and re-enabling the drawer on my detail/child views, so that swiping triggers iOS' "go back" gesture. I don't have any issues with the drawer not working afterwards.

I don't know exactly how you're using it, but maybe you can use my code below.

The following code is from my detail/child ViewController.

```swift
override func viewWillAppear(animated: Bool) {
    super.viewDidAppear(animated)
    
    let appDelegate: AppDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
    appDelegate.drawerController.openDrawerGestureModeMask = .Custom
}

override func viewWillDisappear(animated: Bool) {
    super.viewWillDisappear(animated)
    
    let appDelegate: AppDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
    appDelegate.drawerController.openDrawerGestureModeMask = .All
}
```

**Comment by shahdhiren** [comment]
This worked like a charm. Thanks :)
