### ISSUE TITLE
changing openDrawerGestureModeMask has no effect

### ISSUE THREAD

**Issue by sasikiran** [sascha/DrawerController#56]
I have this a requirement to disable pan gesture for the drawer controller. So, I did this: 

```
drawer.openDrawerGestureModeMask = .Custom
drawer.closeDrawerGestureModeMask = .All
drawer.gestureShouldRecognizeTouchBlock = { _, _, _ in
      return false
}
```

It still doesn't disable the pan gesture. The only way to do it is to go setupGestureRecognizers() method and write a pan.enabled = false. Am I missing something?

It would be good if openDrawerGestureModeMask has a .None option.

**Comment by sascha** [comment]
@sasikiran I'm a little busy lately. I'm happy to merge a pull request if you create one though.
