### ISSUE TITLE
Inheritance from non-protocol type 'DarwinBoolean'

### ISSUE THREAD

**Issue by patelmm** [sascha/DrawerController#66]
Hello,
I'm using pod version 1.1.1 and swift 3.0 and Xcode 8.
Can you help me for this issue :- "Inheritance from non-protocol type 'DarwinBoolean'"

Thanks in advance.

![screen shot 2016-09-24 at 4 12 55 pm](https://cloud.githubusercontent.com/assets/22412529/18807962/ab333e2e-8272-11e6-80ff-10692f239073.png)

**Comment by sascha** [comment]
I've released DrawerController 2.0.0 with Swift 2.3 support and DrawerController 3.0.0 with Swift 3.0 support.
