### ISSUE TITLE
centerHiddenInteractionMode not Working 

### ISSUE THREAD

**Issue by jitu89** [sascha/DrawerController#69]
Hi ,
I'm trying to disable the userInteraction  of central view controller  by self.drawerController.centerHiddenInteractionMode = .None
But it is not happening 
Any idea ?

Thank You

**Comment by sascha** [comment]
`self.drawerController.centerHiddenInteractionMode = .none` means that you can't interact with the center while one of the drawers is open, it doesn't affect user interaction of the center controller while it is fully visible. If you really want to disable user interaction for the center controller, you could try `self.centerViewController?.view.isUserInteractionEnabled = false`
