### ISSUE TITLE
Optimize compile times

### ISSUE THREAD

**Issue by madhikarma** [sascha/DrawerController#71]
Hi there 

First of all thank you for creating this library!

# Summary 
- `bounceKeyFrameAnimation` take a little while (400 milliseconds) to compile.

# Description 

I've done some profiling of compile times on a Swift project and as well as optimising our application code we found the `bounceKeyFrameAnimation` function  of `DrawerController.swift` to take a bit of  times ~10 x longer than other files we have that are reported as slower to compile. I realise this is small but overall it can add up. 

```411.5ms	...Pods/DrawerController/DrawerController/DrawerController.swift:62:14	private func bounceKeyFrameAnimation(forDistance distance: CGFloat, on view: UIView) -> CAKeyframeAnimation```

# Discussion
- Can we create a dynamic framework target so that developers can build as a framework and link themselves instead of Pods if they choose? Note. they will need to take care to build as a sim and device framework or universal but perhaps we can make a shell script for this. 
- And / or can we optimise the code a bit within this method and profile to see if it compiles quicker 

Let me know what you think and thanks again!

**Comment by madhikarma** [comment]
Let me know if you'd be open to a contribution here.

My guess is this line inside the map is the one that slows down the compiler most 

`NSNumber(value: Float(x / 128 * distance + view.bounds.midX) as Float)`

and if split out may improve things

**Comment by sascha** [comment]
Hi, I've refactored the line as per your suggestions. Compile times for that method are now < 100 ms. Thanks!
