### ISSUE TITLE
Initializer of AnimatedMenuButton with color parameter is internal

### ISSUE THREAD

**Issue by rostopira** [sascha/DrawerController#77]
I would like to change stroke color to green and with 45x45 rect, but following code:
```
let drawerButton = AnimatedMenuButton(
       frame: CGRect(x: 0, y: 0, width: 45, height: 45),
       strokeColor: UIColor(hex: 0xC7A0))
```
Gives me error `'AnimatedMenuButton' initializer is inacessible due to 'internal' protection level`
Please, make it public

**Comment by maltebaumann** [comment]
Hey there, sorry for the delay. Please provide a pull request, then we can merge in the change. Thanks!
