### ISSUE TITLE
Swift 3.1 support

### ISSUE THREAD

**Issue by chrisw73** [sascha/DrawerController#79]
Just 4 warnings regarding M_PI => Double.pi and M_PI_2 => Double.pie / 2 ... Any plans for a fix release? :-)

**Comment by maltebaumann** [comment]
Hi, feel free to open a pull request :)

**Comment by chrisw73** [comment]
Tried to, but got an "Authentication Failed" "You may not have permission to access DrawerController. Check Preferences to make sure you’re still logged in." using GitHub Desktop on Mac OS... I am logged in using pasic auth...

**Comment by maltebaumann** [comment]
You need to fork this repository, make your changes in your fork and submit a pull request from there. Take a look here: https://guides.github.com/activities/contributing-to-open-source/ (starting at the *Pull Request* section. Thanks again!

**Comment by chrisw73** [comment]
Finally ;-)
