### ISSUE TITLE
DrawerDefaultWidth aka _maximumLeftDrawerWidth aka _maximumRightDrawerWidth

### ISSUE THREAD

**Issue by aornano** [sascha/DrawerController#88]
The default value is setted to 280.0 and this one is correct only for the iPhone 5s or less.
I suggest to modify the source line:

**DrawerController.swift:**

`private let DrawerDefaultWidth: CGFloat = 280.0`

to

`private let DrawerDefaultWidth: CGFloat = UIScreen.main.bounds.width-40.0`

P.S. This project is very cool, compliments.

**Comment by maltebaumann** [comment]
Hey, thanks for your suggestion and you're right of course. Could you provide a pull request? Thanks!

**Comment by aornano** [comment]
Yeah, this is right but not enough, I mean, I was thinking also when the app change it's orientation to  portrait to landscape: it could be very cool if the DrawerDefaultWidth become a variable , not a constant, to intercept the orientation change delegate and change it's value.

**Comment by maltebaumann** [comment]
Actually, I was wrong. Your code snippet just describes the DrawerControllers default value, but the left/right drawer width is already exposed via the `maximumLeftDrawerWidth` and `maximumRightDrawerWidth` properties. These are variables and may be changed at any time, so you may handle rotation and different screen sizes yourself by updating the variables. I'm closing this, as there is no need for any enhancement to the DrawerController itself.
